
stages:          # List of stages for jobs, and their order of execution
  - build

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  image: ubuntu:22.04
  before_script:
    - apt update
    - apt upgrade -y
    - apt install -y build-essential libfmt-dev pkg-config
    - apt install -y cmake catch doxygen libboost-all-dev libfabric-dev libibverbs-dev libkmod-dev libnuma-dev libpci-dev librdmacm-dev libtool-bin libssl-dev libzmq3-dev
  script:
    - mkdir build && cd build && cmake ..
    - make
